# Generated by Django 4.2.7 on 2023-11-08 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='creado',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='fechaterminada',
            new_name='fecha_terminada',
        ),
    ]
